### ISSUE TITLE
OTAPIv3 Client; Windows Launcher: Fails to launch due to missing libwinpthread-1.dll

### ISSUE THREAD

**Issue by 0x3fcf1bbd** [DeathCradle/Open-Terraria-API#52]
**Describe the bug**
OTAPIv3 client fails to launch due to `libwinpthread-1.dll` being missing.

**To Reproduce**
- Download the windows launcher from https://github.com/DeathCradle/Open-Terraria-API/releases/tag/launcher-windows.
- Extract it, and run OTAPI.Client.Launcher.exe.
- Press the "Build OTAPI" button, and wait until the operation finishes.
- Then, press the "Launch modded Terraria (otapi)" button.
->Exception occurs, and game fails to launch.

**Expected behavior**
The game launches without issues.

**Stack trace**
``System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load DLL '.\x64\FNA3D.dll' or one of its dependencies: The specified module couldn't be resolved. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at OTAPI.Client.Launcher.Actions.OTAPI.ResolveNativeDep(String libraryName, Assembly assembly, Nullable`1 searchPath) in D:\a\Open-Terraria-API\Open-Terraria-API\OTAPI.Client.Launcher\Actions\OTAPI.cs:line 190
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\Open-Terraria-API\Open-Terraria-API\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 284
   at Microsoft.Xna.Framework.Game..ctor() in D:\a\Open-Terraria-API\Open-Terraria-API\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor()
   at HostGame..ctor() in csharp\plugins\modules\otapi-runtime\HostGame.cs:line 37
   at HostGamePlugin.<>c.<PatchClient>b__3_0() in csharp\plugins\modules\otapi-runtime\HostGamePlugin.cs:line 64
   at OTAPI.Hooks.Main.InvokeCreate() in patchtime\csharp\plugins\toplevel\otapi\HookMainCtor.Client.cs:line 60
   at Terraria.Program.orig_LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in patchtime\csharp\plugins\patches\otapi\Terraria.Program.Both.cs:line 139
   at Terraria.WindowsLaunch.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OTAPI.Client.Launcher.Actions.OTAPI.Launch(String[] args) in D:\a\Open-Terraria-API\Open-Terraria-API\OTAPI.Client.Launcher\Actions\OTAPI.cs:line 56
   at OTAPI.Client.Launcher.Program.Main(String[] args) in D:\a\Open-Terraria-API\Open-Terraria-API\OTAPI.Client.Launcher\Program.cs:line 66``

**Platform and patch info (please complete the following information):**
 - OS: Windows 8.1
 - Assembly and version you are patching: Terraria.exe 1.4.3.2
 - Version of OTAPI/git commit: `57114e0`
 - .NET runtime: .NET 6

**Additional context**
I looked up what happened using ProcMon, and it seems that it is looking for `libwinpthread-1.dll`. Maybe my system is outdated and the DLL is part of all newer system versions? I don't know. 
For now I installed mingw-w64, and copied the DLL to OTAPI's folder, and it works. Kind of "resolved", but I think it'd be better if OTAPI could fetch all the libraries it needs so the user doesn't have to go hunt DLLs on their own.

**Comment by DeathCradle** [comment]
yikes, can confirm this now too.
this is due to the fna libs being updated within the last day. will need to investigate.

**Comment by DeathCradle** [comment]
@0x3fcf1bbd i have reverted to the previous libs and this appears to have fixed it for me, if you download the latest release are you able to confirm it works your end too?

**Comment by 0x3fcf1bbd** [comment]
Yes, I confirm it fixed the issue.

**Comment by 0x3fcf1bbd** [comment]
Wait I can close issue I forgot
